version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=medusaronwell
      - POSTGRES_USER=medusaronwell
      - POSTGRES_PASSWORD=12345
    ports:
      - 5434:5432
volumes:
  postgres-db: